// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDABq8IjyPc_Fp9htLd0gc_lZsH3IozFFw',
    appId: '1:541882838462:web:53e258a8f49114c0545def',
    messagingSenderId: '541882838462',
    projectId: 'euro24-631f3',
    authDomain: 'euro24-631f3.firebaseapp.com',
    databaseURL: 'https://euro24-631f3-default-rtdb.firebaseio.com',
    storageBucket: 'euro24-631f3.appspot.com',
    measurementId: 'G-4TZL5MPCPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaj7NNYJAjXkTgLqAZhTMie9j8jzbKdqA',
    appId: '1:541882838462:android:69277489d6a20957545def',
    messagingSenderId: '541882838462',
    projectId: 'euro24-631f3',
    databaseURL: 'https://euro24-631f3-default-rtdb.firebaseio.com',
    storageBucket: 'euro24-631f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-LETZlocCknTlGtZhRBzotlHr0tTeOpk',
    appId: '1:541882838462:ios:200c638ab8f9216a545def',
    messagingSenderId: '541882838462',
    projectId: 'euro24-631f3',
    databaseURL: 'https://euro24-631f3-default-rtdb.firebaseio.com',
    storageBucket: 'euro24-631f3.appspot.com',
    iosClientId: '541882838462-s1rpe73i7rlstphp6bv1j9pronpuvobg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-LETZlocCknTlGtZhRBzotlHr0tTeOpk',
    appId: '1:541882838462:ios:200c638ab8f9216a545def',
    messagingSenderId: '541882838462',
    projectId: 'euro24-631f3',
    databaseURL: 'https://euro24-631f3-default-rtdb.firebaseio.com',
    storageBucket: 'euro24-631f3.appspot.com',
    iosClientId: '541882838462-s1rpe73i7rlstphp6bv1j9pronpuvobg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDABq8IjyPc_Fp9htLd0gc_lZsH3IozFFw',
    appId: '1:541882838462:web:fccea166483e0cac545def',
    messagingSenderId: '541882838462',
    projectId: 'euro24-631f3',
    authDomain: 'euro24-631f3.firebaseapp.com',
    databaseURL: 'https://euro24-631f3-default-rtdb.firebaseio.com',
    storageBucket: 'euro24-631f3.appspot.com',
    measurementId: 'G-GJMDZZRWPC',
  );
}
